apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: esql-transformation
  labels: {}
spec:
  adminServerSecure: false
  barURL: >-
    https://github.com/Martist/pipeline-ace/raw/fee610eef70d2437f2bb17348a0c1d0117c0ca72/bars/Transformation_ESQL.bar
  configurations:
    - github-barauth
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-C79J9U
    use: AppConnectEnterpriseProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0'
